name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        python install_spacy_model.py
        
    - name: Create necessary directories
      run: |
        mkdir -p maps
        mkdir -p voice
        
    - name: Run tests (пример)
      run: |
        # Здесь могут быть ваши тесты
        echo "Tests would run here"
